"""Mutate ESDL KPI / asset values in-place and return a fresh base64 payload.

The base scenario at ``datacenter_bess_scenario.esdl`` is regenerated by the
upstream script ``datacenter_bess_scenario.py``; this module only edits the
values that the experimental sweeps perturb, so that each run still
corresponds to a single ESDL file that can be persisted for provenance.
"""
from __future__ import annotations

import base64
import copy
from pathlib import Path
from typing import Any

from esdl.esdl_handler import EnergySystemHandler


NETWORK_KPI_KEYS = {
    "w_unserved", "w_carbon", "w_price", "w_effort", "w_soc_low",
    "soc_baseline",
    "enable_battery", "enable_backup_generator", "enable_renewable_service",
    "enable_change_management", "enable_goal_management", "enable_mandate",
    "mpc_soc_drift_threshold", "mpc_demand_spike_threshold",
    "mpc_horizon_steps", "mpc_replan_cooldown",
    "forecast_sigma_ci", "forecast_sigma_p_dc", "forecast_sigma_price",
    "forecast_seed",
    "backup_co2_factor", "backup_cost_eur_per_kwh",
    "sim_seed",
}


def _set_network_kpi(esh: EnergySystemHandler, name: str, value: float) -> None:
    es = esh.get_energy_system()
    for obj in es.eAllContents():
        eClass = getattr(obj, "eClass", None)
        if eClass and eClass.name == "ElectricityNetwork":
            if obj.KPIs is None:
                continue
            for kpi in obj.KPIs.kpi:
                if getattr(kpi, "name", None) == name:
                    kpi.value = float(value)
                    return
    raise KeyError(f"KPI '{name}' not found on any ElectricityNetwork asset")


def _set_asset_attr(esh: EnergySystemHandler, eclass_name: str, attr: str, value: float) -> None:
    es = esh.get_energy_system()
    for obj in es.eAllContents():
        eClass = getattr(obj, "eClass", None)
        if eClass and eClass.name == eclass_name:
            setattr(obj, attr, value)
            return
    raise KeyError(f"No asset of class '{eclass_name}' found")


def mutate_esdl(base_path: Path, overrides: dict[str, Any], out_path: Path) -> str:
    """Load base ESDL, apply the override dict, write the variant, return base64.

    The override dict accepts the following keys:
      Objective weights (Axis 1):
        w_unserved, w_carbon, w_price, w_effort, w_soc_low, soc_baseline
      Controller (Axis 5):
        enable_change_management, enable_goal_management,
        mpc_soc_drift_threshold, mpc_demand_spike_threshold,
        mpc_horizon_steps, mpc_replan_cooldown
      Forecast (Axis 6):
        forecast_sigma_ci, forecast_sigma_p_dc, forecast_sigma_price, forecast_seed
      Backup Scope-1 accounting (Axis 4 / scope-shift scenario):
        backup_co2_factor, backup_cost_eur_per_kwh
      Monte-Carlo seed (multi-seed robustness study):
        sim_seed
      Physical (Axes 2, 3, 4, grid-limit) — pass the appropriate key:
        battery_capacity_wh, battery_max_rate_w
        pv_power_w
        backup_power_w
        grid_power_w   (transformer/connection capacity → import limit)
    """
    esh = EnergySystemHandler()
    esh.load_file(str(base_path))

    for k, v in overrides.items():
        if k in NETWORK_KPI_KEYS:
            _set_network_kpi(esh, k, v)
        elif k == "battery_capacity_wh":
            _set_asset_attr(esh, "Battery", "capacity", float(v))
        elif k == "battery_max_rate_w":
            _set_asset_attr(esh, "Battery", "maxChargeRate", float(v))
            _set_asset_attr(esh, "Battery", "maxDischargeRate", float(v))
        elif k == "pv_power_w":
            _set_asset_attr(esh, "PVInstallation", "power", float(v))
        elif k == "backup_power_w":
            _set_asset_attr(esh, "GasProducer", "power", float(v))
        elif k == "grid_power_w":
            _set_asset_attr(esh, "PowerPlant", "power", float(v))
        else:
            raise KeyError(f"Unknown ESDL override key: {k}")

    esh.save(filename=str(out_path))
    return base64.b64encode(out_path.read_bytes()).decode("utf-8")
