"""Render pgfplots .tex snippets from the sweep CSVs into zthesis/figures/.

Each snippet is a self-contained ``figure`` environment using ``pgfplots``
and (for axis 5 and the cross-axis cloud) plain TikZ. Add to the thesis
preamble:

    \\usepackage{pgfplots}
    \\pgfplotsset{compat=1.18}
    \\usetikzlibrary{patterns}
"""
from __future__ import annotations

import csv
import math
from pathlib import Path

HERE = Path(__file__).parent
RESULTS = HERE / "results"
THESIS_DIR = HERE.parent.parent.parent / "zthesis"
FIG_DIR = THESIS_DIR / "figures"


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _f(d: dict[str, str], key: str, default: float = float("nan")) -> float:
    v = d.get(key, "")
    if v in ("", None, "nan"):
        return default
    try:
        return float(v)
    except ValueError:
        return default


def _is_valid(r: dict[str, str]) -> bool:
    return not math.isnan(_f(r, "Cumulative_Carbon_g"))


def _write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


# ── Axis 1: Objective-weight sweep — 2 panels (Pareto + breakdown bars) ────
def fig_axis1() -> None:
    rows = [r for r in _read_csv(RESULTS / "axis1_pareto.csv") if _is_valid(r)]
    if not rows:
        return

    # Panel A: zoomed Pareto with baseline anchor far away
    base_k = _f(rows[0], "Cumulative_EqualService_Cost_EUR")
    base_c = _f(rows[0], "Cumulative_EqualService_Carbon_g") / 1e6
    pts = [(_f(r, "Cumulative_Cost_EUR"), _f(r, "Cumulative_Carbon_g") / 1e6,
            r["label"]) for r in rows]
    coords = "\n".join(f"    ({c:.0f},{co:.3f})" for c, co, _ in pts)
    labels = "\n".join(
        f"    \\node[font=\\tiny, anchor=west] at (axis cs:{c:.0f},{co:.3f}) "
        f"{{\\,{lbl.replace('_', '\\_')}}};"
        for c, co, lbl in pts
    )

    # Panel B: per-metric % difference vs baseline
    bar_rows = []
    for r in rows:
        k = _f(r, "Cumulative_Cost_EUR")
        c = _f(r, "Cumulative_Carbon_g")
        u = _f(r, "Cumulative_Unserved_kWh")
        dK = (k - base_k) / base_k * 100
        dC = (c - base_c * 1e6) / (base_c * 1e6) * 100
        bar_rows.append((r["label"], dK, dC, u))
    n = len(bar_rows)
    xt = ",".join(str(i) for i in range(n))
    xtl = ",".join(f"\\tiny {b[0].replace('_', '\\_')}" for b in bar_rows)
    dK_pts = " ".join(f"({i},{b[1]:.2f})" for i, b in enumerate(bar_rows))
    dC_pts = " ".join(f"({i},{b[2]:.2f})" for i, b in enumerate(bar_rows))

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=panelA,
    width=0.82\\textwidth, height=6.0cm,
    xlabel={{$\\widetilde{{K}}_T$ [EUR]}},
    ylabel={{$\\widetilde{{C}}_T$ [tCO$_2$]}},
    grid=major, grid style={{gray!15}},
    title={{(a) Realised front + baseline anchor}}, title style={{font=\\small}},
    legend pos=south east, legend style={{font=\\tiny}},
]
\\addplot[mark=*, mark size=2pt, blue!70!black, very thick]
  coordinates {{
{coords}
}};
\\addlegendentry{{Sweep runs}}
\\addplot[mark=square*, mark size=4pt, red] coordinates {{({base_k:.0f},{base_c:.3f})}};
\\addlegendentry{{equal-service baseline}}
{labels}
\\end{{axis}}
\\begin{{axis}}[
    name=panelB, at={{(panelA.south west)}}, anchor=north west, yshift=-20mm,
    width=0.82\\textwidth, height=6.0cm,
    ybar=2pt, bar width=4pt,
    xtick={{{xt}}}, xticklabels={{{xtl}}}, x tick label style={{rotate=40, anchor=east}},
    ylabel={{\\% change vs baseline}},
    title={{(b) Carbon \\& cost overhead per run}},
    title style={{font=\\small}},
    grid=major, grid style={{gray!15}},
    legend style={{font=\\tiny, at={{(0.5,-0.45)}}, anchor=north, legend columns=2}},
    enlargelimits=0.12,
]
\\addplot[fill=orange!70, draw=orange!90!black] coordinates {{ {dK_pts} }};
\\addlegendentry{{Cost overhead (\\%)}}
\\addplot[fill=blue!60, draw=blue!80!black] coordinates {{ {dC_pts} }};
\\addlegendentry{{Carbon overhead (\\%)}}
\\draw[gray, dashed] (axis cs:-1,0) -- (axis cs:{n},0);
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Objective-weight sweep: realised cost--carbon scatter (a dominated cluster, not a Pareto front) and per-run overhead relative to the equal-service baseline.}}
\\label{{fig:res_pareto}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis1_pareto.tex", body)


# ── Axis 2: BESS sizing — 3 panels (carbon, cost, unserved) ────────────────
def _three_panel(rows, x_key, x_label, x_unit, caption, label):
    if not rows:
        return ""

    def pts(metric_fn):
        return "\n".join(
            f"    ({_f(r, x_key):g},{metric_fn(r):.3f})" for r in rows
        )

    coords_c = pts(lambda r: _f(r, "Cumulative_Carbon_g") / 1e6)
    coords_k = pts(lambda r: _f(r, "Cumulative_Cost_EUR"))
    coords_u = pts(lambda r: _f(r, "Cumulative_Unserved_kWh") / 1000.0)
    # Equal-service baseline (B) is per-row: it serves the same load the EMS
    # served at that point, so it moves with capacity rather than being a single
    # flat line. Plotting it per-row keeps the figure consistent with the
    # per-row percentages in the accompanying table.
    base_coords_c = pts(lambda r: _f(r, "Cumulative_EqualService_Carbon_g") / 1e6)
    base_coords_k = pts(lambda r: _f(r, "Cumulative_EqualService_Cost_EUR"))
    # Reliability reference for unserved energy is the PASSIVE no-battery
    # facility (same PV, same grid limit), not the equal-service baseline (which
    # by construction sheds exactly what the EMS sheds). The gap between this and
    # the EMS curve is the load the battery rescues.
    base_coords_u = pts(lambda r: _f(r, "Cumulative_Passive_Unserved_kWh") / 1000.0)

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.68\\textwidth, height=5.0cm,
    xlabel={{{x_label} {x_unit}}}, ylabel={{$\\widetilde{{C}}_T$ [tCO$_2$]}},
    grid=major, grid style={{gray!15}}, title={{(a) Carbon}}, title style={{font=\\small}},
    legend pos=north west, legend style={{font=\\tiny}},
]
\\addplot[mark=*, blue!70!black, very thick] coordinates {{
{coords_c}
}};
\\addlegendentry{{EMS}}
\\addplot[mark=o, red, dashed, thick] coordinates {{
{base_coords_c}
}};
\\addlegendentry{{equal-service baseline}}
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-16mm,
    width=0.68\\textwidth, height=5.0cm,
    xlabel={{{x_label} {x_unit}}}, ylabel={{$\\widetilde{{K}}_T$ [EUR]}},
    grid=major, grid style={{gray!15}}, title={{(b) Cost}}, title style={{font=\\small}},
    legend pos=north west, legend style={{font=\\tiny}},
]
\\addplot[mark=*, orange!80!black, very thick] coordinates {{
{coords_k}
}};
\\addlegendentry{{EMS}}
\\addplot[mark=o, red, dashed, thick] coordinates {{
{base_coords_k}
}};
\\addlegendentry{{equal-service baseline}}
\\end{{axis}}
\\begin{{axis}}[
    name=p3, at={{(p2.south west)}}, anchor=north west, yshift=-16mm,
    width=0.68\\textwidth, height=5.0cm,
    xlabel={{{x_label} {x_unit}}}, ylabel={{$\\widetilde{{L}}_{{unserved,T}}$ [MWh]}},
    grid=major, grid style={{gray!15}}, title={{(c) Unserved energy}},
    title style={{font=\\small}}, ymin=0,
    legend pos=north east, legend style={{font=\\tiny}},
]
\\addplot[mark=*, red!80!black, very thick] coordinates {{
{coords_u}
}};
\\addlegendentry{{EMS}}
\\addplot[mark=o, gray!60!black, dashed, thick] coordinates {{
{base_coords_u}
}};
\\addlegendentry{{passive (no battery)}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{{caption}}}
\\label{{{label}}}
\\end{{figure}}
"""
    return body


def fig_axis2() -> None:
    rows = [r for r in _read_csv(RESULTS / "axis2_bess.csv") if _is_valid(r)]
    if not rows:
        return
    cap = (r"BESS sizing sweep: cumulative carbon, cost, and unserved energy "
           r"vs.\ nameplate capacity at carbon-anchored objective.")
    body = _three_panel(rows, "capacity_mwh", "$E_{bat}$", "[MWh]",
                        cap, "fig:res_bess")
    _write(FIG_DIR / "fig_axis2_bess.tex", body)


def fig_axis3() -> None:
    rows = [r for r in _read_csv(RESULTS / "axis3_pv.csv") if _is_valid(r)]
    if not rows:
        return
    cap = (r"PV sizing sweep: cumulative carbon, cost, and unserved energy "
           r"vs.\ installed PV capacity, with BESS held at 4\,MWh.")
    body = _three_panel(rows, "pv_mw", "PV capacity", "[MW]",
                        cap, "fig:res_pv")
    _write(FIG_DIR / "fig_axis3_pv.tex", body)


# ── Axis 4: backup generation — special-case 2 panels ──────────────────────
def fig_axis4() -> None:
    rows = [r for r in _read_csv(RESULTS / "axis4_backup.csv") if _is_valid(r)]
    if not rows:
        return
    base_c = _f(rows[0], "Cumulative_EqualService_Carbon_g") / 1e6
    pts_c = "\n".join(
        f"    ({_f(r, 'backup_mw'):g},{_f(r, 'Cumulative_Carbon_g') / 1e6:.3f})"
        for r in rows
    )
    pts_u = "\n".join(
        f"    ({_f(r, 'backup_mw'):g},{_f(r, 'Cumulative_Unserved_kWh') / 1000.0:.3f})"
        for r in rows
    )

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.78\\textwidth, height=5.5cm,
    xlabel={{Backup capacity [MW]}}, ylabel={{$\\widetilde{{C}}_T$ [tCO$_2$]}},
    grid=major, grid style={{gray!15}}, title={{(a) Carbon}}, title style={{font=\\small}},
]
\\addplot[mark=*, blue!70!black, very thick] coordinates {{
{pts_c}
}};
\\addplot[red, dashed, thick] coordinates {{(0,{base_c:.3f}) (10,{base_c:.3f})}};
\\node[red, font=\\tiny, anchor=south] at (axis cs:8,{base_c:.3f}) {{equal-service}};
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-18mm,
    width=0.78\\textwidth, height=5.5cm,
    xlabel={{Backup capacity [MW]}}, ylabel={{$\\widetilde{{L}}_{{unserved,T}}$ [MWh]}},
    grid=major, grid style={{gray!15}}, title={{(b) Unserved energy}},
    title style={{font=\\small}}, ymin=0,
]
\\addplot[mark=*, red!80!black, very thick] coordinates {{
{pts_u}
}};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Backup-generator sweep: cumulative carbon and unserved energy vs.\\ generator nameplate capacity.}}
\\label{{fig:res_backup}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis4_backup.tex", body)


# ── Axis 5: MPC threshold sweep — 2 panels (heatmap + replan bars) ─────────
def _static_baseline_sentence(static_unserved: float) -> str:
    if math.isnan(static_unserved):
        return ("The Static-Plan baseline run also hit the broker race and is "
                "not reported.")
    return (f"The Static-Plan baseline (no MPC) accrues "
            f"$\\widetilde{{L}}_{{unserved,T}}\\approx{static_unserved:.0f}$\\,kWh, "
            "in the same range as the swept MPC cells — the MPC's replanning "
            "provides only marginal unserved-load improvement on the realised "
            "forecast-error trace, an empirical contrast against H4.")


def fig_axis5() -> None:
    rows = _read_csv(RESULTS / "axis5_mpc.csv")
    if not rows:
        return
    drifts = [1.0, 5.0, 10.0, 20.0]
    spikes = [0.05, 0.10, 0.20, 0.50]
    cells: dict[tuple[float, float], dict[str, float]] = {}
    static_unserved = float("nan")
    static_replans = float("nan")
    for r in rows:
        if r["label"] == "mpc_static":
            static_unserved = _f(r, "Cumulative_Unserved_kWh")
            static_replans = _f(r, "Replan_Count")
            continue
        d = _f(r, "drift_pct")
        s = _f(r, "spike_frac")
        u = _f(r, "Cumulative_Unserved_kWh")
        rp = _f(r, "Replan_Count")
        if not math.isnan(u):
            cells[(d, s)] = {"unserved": u, "replans": rp}

    if not cells:
        return
    unservs = [c["unserved"] for c in cells.values()]
    u_min, u_max = min(unservs), max(unservs)
    u_range = max(u_max - u_min, 1.0)

    cell_w, cell_h = 1.6, 1.1
    rect_lines, replan_pts = [], []
    for j, d in enumerate(drifts):
        for i, s in enumerate(spikes):
            x0, y0 = i * cell_w, j * cell_h
            x1, y1 = x0 + cell_w, y0 + cell_h
            xm, ym = (x0 + x1) / 2, (y0 + y1) / 2
            if (d, s) in cells:
                c = cells[(d, s)]
                # Stretch colour over the actual range so variation is visible.
                shade = int(15 + 75 * (c["unserved"] - u_min) / u_range)
                rect_lines.append(
                    f"  \\fill[blue!{shade}!white] ({x0:.2f},{y0:.2f}) "
                    f"rectangle ({x1:.2f},{y1:.2f});"
                )
                txt_color = "white" if shade > 50 else "black"
                rect_lines.append(
                    f"  \\node[font=\\tiny, {txt_color}, anchor=center] at "
                    f"({xm:.2f},{ym:.2f}) "
                    f"{{{c['unserved'] / 1000:.1f}\\,MWh\\\\"
                    f"\\scriptsize {c['replans']:.0f} replans}};"
                )
                replan_pts.append((d, s, c["replans"]))
            else:
                rect_lines.append(
                    f"  \\fill[pattern=north east lines, pattern color=gray!50] "
                    f"({x0:.2f},{y0:.2f}) rectangle ({x1:.2f},{y1:.2f});"
                )
                rect_lines.append(
                    f"  \\node[font=\\tiny, gray!60!black, anchor=center] at "
                    f"({xm:.2f},{ym:.2f}) {{\\itshape no data}};"
                )

    xtick_lines = [
        f"  \\node[font=\\scriptsize, anchor=north] at "
        f"({i * cell_w + cell_w / 2:.2f},-0.2) {{{s:g}}};"
        for i, s in enumerate(spikes)
    ]
    ytick_lines = [
        f"  \\node[font=\\scriptsize, anchor=east] at "
        f"(-0.15,{j * cell_h + cell_h / 2:.2f}) {{{d:g}\\%}};"
        for j, d in enumerate(drifts)
    ]
    total_w, total_h = len(spikes) * cell_w, len(drifts) * cell_h

    # Replan-count panel: bar per cell, x = drift index, group by spike.
    bar_pts_per_spike: dict[float, list[str]] = {s: [] for s in spikes}
    for d, s, rp in replan_pts:
        bar_pts_per_spike[s].append(f"({d:g},{rp:.0f})")
    # Add static baseline as a horizontal rule
    static_line = ""
    if not math.isnan(static_replans):
        static_line = (
            f"\\addplot[red, dashed, thick] coordinates {{(0,{static_replans:.0f}) "
            f"(25,{static_replans:.0f})}};\n"
            f"\\node[red, font=\\tiny, anchor=south east] at "
            f"(axis cs:25,{static_replans:.0f}) {{Static plan ({static_replans:.0f})}};\n"
        )
    bar_plots = ""
    colors = ["blue!60", "orange!70", "green!60!black", "purple!70"]
    for color, (s, pts) in zip(colors, bar_pts_per_spike.items()):
        if not pts:
            continue
        bar_plots += (
            f"\\addplot+[mark=*, mark size=2pt, {color}, thick] "
            f"coordinates {{ {' '.join(pts)} }};\n"
            f"\\addlegendentry{{spike={s:g}}}\n"
        )

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}[align=center, pattern color=gray!50]
{chr(10).join(rect_lines)}
  \\draw[gray!50] (0,0) rectangle ({total_w:.2f},{total_h:.2f});
{chr(10).join(xtick_lines)}
{chr(10).join(ytick_lines)}
  \\node[font=\\small, anchor=north] at ({total_w / 2:.2f},-0.85)
    {{Demand-spike threshold (fraction)}};
  \\node[font=\\small, rotate=90, anchor=south] at (-0.95,{total_h / 2:.2f})
    {{SOC-drift threshold}};
\\end{{tikzpicture}}
\\\\[6pt]
\\begin{{tikzpicture}}
\\begin{{axis}}[
    width=0.75\\textwidth, height=4.5cm,
    xlabel={{SOC-drift threshold [\\%]}}, ylabel={{Replan count}},
    grid=major, grid style={{gray!15}},
    legend style={{font=\\tiny, at={{(1.02,1)}}, anchor=north west}},
    title={{(b) MPC replan frequency vs. threshold}}, title style={{font=\\small}},
    ymin=0, ymax=1300, xmin=0, xmax=25,
]
{bar_plots}{static_line}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{MPC threshold sweep: unserved energy and replan count across SOC-drift and demand-spike threshold combinations.}}
\\label{{fig:res_mpc}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis5_mpc.tex", body)


# ── New Figure 6: Cross-axis Pareto cloud + baseline ───────────────────────
def fig_combined_pareto() -> None:
    axes = [
        ("axis1_pareto.csv", "Axis 1 (weights)",  "blue!60",   "*"),
        ("axis2_bess.csv",   "Axis 2 (BESS)",     "red!70",    "triangle*"),
        ("axis3_pv.csv",     "Axis 3 (PV)",       "green!60!black", "square*"),
        ("axis4_backup.csv", "Axis 4 (backup)",   "orange!80",  "diamond*"),
        ("axis5_mpc.csv",    "Axis 5 (MPC)",      "purple!70",  "x"),
    ]
    plots: list[str] = []
    base_k = base_c = None
    for fname, name, color, mark in axes:
        rows = [r for r in _read_csv(RESULTS / fname) if _is_valid(r)]
        if not rows:
            continue
        if base_k is None:
            base_k = _f(rows[0], "Cumulative_EqualService_Cost_EUR")
            base_c = _f(rows[0], "Cumulative_EqualService_Carbon_g") / 1e6
        coords = " ".join(
            f"({_f(r, 'Cumulative_Cost_EUR'):.0f},{_f(r, 'Cumulative_Carbon_g') / 1e6:.3f})"
            for r in rows
        )
        plots.append(
            f"\\addplot[only marks, mark={mark}, mark size=2.5pt, {color}] "
            f"coordinates {{ {coords} }};\n\\addlegendentry{{{name}}}"
        )
    if base_k is None:
        return

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    width=0.78\\textwidth, height=8.0cm,
    xlabel={{Cumulative cost $\\widetilde{{K}}_T$ [EUR]}},
    ylabel={{Cumulative carbon $\\widetilde{{C}}_T$ [tCO$_2$]}},
    grid=major, grid style={{gray!15}},
    legend pos=south east, legend style={{font=\\scriptsize}},
]
{chr(10).join(plots)}
\\addplot[only marks, mark=square*, mark size=5pt, red] coordinates {{({base_k:.0f},{base_c:.3f})}};
\\addlegendentry{{equal-service baseline ({base_k:.0f}\\,EUR; {base_c:.0f}\\,tCO$_2$)}}
\\node[red, font=\\tiny, anchor=west] at (axis cs:{base_k:.0f},{base_c:.3f}) {{\\,baseline}};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{All sweep runs on the cumulative cost--carbon plane (a scatter against the equal-service baseline anchor, not a Pareto surface); only the storage axis produces a spread of non-dominated points.}}
\\label{{fig:res_combined_pareto}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_combined_pareto.tex", body)


# ── New Figure 7: Controller overhead — bar chart of % deltas ──────────────
def fig_overhead() -> None:
    """Per-axis "best run" overhead vs baseline, bar chart."""
    summaries: list[tuple[str, float, float, float]] = []  # label, dC%, dK%, U
    for fname, name in [
        ("axis1_pareto.csv", "Axis 1 best (p\\_strong)"),
        ("axis2_bess.csv",   "Axis 2 best (16 MWh)"),
        ("axis3_pv.csv",     "Axis 3 best (500 kW)"),
        ("axis4_backup.csv", "Axis 4 (0 MW, ref)"),
        ("axis5_mpc.csv",    "Axis 5 best (d10/s0.2)"),
    ]:
        rows = [r for r in _read_csv(RESULTS / fname) if _is_valid(r)]
        if not rows:
            continue
        # Pick the row with lowest carbon as the "best" for the axis.
        best = min(rows, key=lambda r: _f(r, "Cumulative_Carbon_g"))
        base_c = _f(best, "Cumulative_EqualService_Carbon_g")
        base_k = _f(best, "Cumulative_EqualService_Cost_EUR")
        dC = (_f(best, "Cumulative_Carbon_g") - base_c) / base_c * 100
        dK = (_f(best, "Cumulative_Cost_EUR") - base_k) / base_k * 100
        u = _f(best, "Cumulative_Unserved_kWh") / 1000.0
        summaries.append((name, dC, dK, u))

    n = len(summaries)
    xt = ",".join(str(i) for i in range(n))
    xtl = ",".join(f"\\tiny {s[0]}" for s in summaries)
    dc_pts = " ".join(f"({i},{s[1]:.2f})" for i, s in enumerate(summaries))
    dk_pts = " ".join(f"({i},{s[2]:.2f})" for i, s in enumerate(summaries))
    u_pts  = " ".join(f"({i},{s[3]:.2f})" for i, s in enumerate(summaries))

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.78\\textwidth, height=5.5cm,
    ybar=2pt, bar width=6pt,
    xtick={{{xt}}}, xticklabels={{{xtl}}}, x tick label style={{rotate=35, anchor=east}},
    ylabel={{\\% change vs equal-service baseline}},
    grid=major, grid style={{gray!15}},
    title={{(a) Carbon \\& cost overhead}}, title style={{font=\\small}},
    legend style={{font=\\tiny, at={{(0.5,-0.5)}}, anchor=north, legend columns=2}},
    enlargelimits=0.18,
]
\\addplot[fill=blue!60, draw=blue!80!black] coordinates {{ {dc_pts} }};
\\addlegendentry{{Carbon $\\Delta$}}
\\addplot[fill=orange!70, draw=orange!90!black] coordinates {{ {dk_pts} }};
\\addlegendentry{{Cost $\\Delta$}}
\\draw[gray, dashed] (axis cs:-1,0) -- (axis cs:{n},0);
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-32mm,
    width=0.78\\textwidth, height=5.5cm,
    ybar, bar width=14pt,
    xtick={{{xt}}}, xticklabels={{{xtl}}}, x tick label style={{rotate=35, anchor=east}},
    ylabel={{$\\widetilde{{L}}_{{unserved,T}}$ [MWh]}},
    grid=major, grid style={{gray!15}},
    title={{(b) Unserved energy}}, title style={{font=\\small}}, ymin=0,
    enlargelimits=0.18,
]
\\addplot[fill=red!70, draw=red!85!black] coordinates {{ {u_pts} }};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Best-of-axis carbon, cost, and unserved-energy overhead relative to the equal-service baseline.}}
\\label{{fig:res_overhead}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_overhead.tex", body)


# ── Axis 6: Seasonal sensitivity ───────────────────────────────────────────
def fig_axis6() -> None:
    """Two-panel seasonal figure.

    Panel (a): carbon-saving % and cost-saving % vs equal-service baseline by season.
    Panel (b): cumulative PV yield [MWh] by season — shows *why* summer saves more.
    X-axis groups: Winter (Jan–Feb), Spring (Apr–May), Summer (Jul–Aug), Autumn (Oct–Nov).
    """
    rows = [r for r in _read_csv(RESULTS / "axis6_seasonal.csv") if _is_valid(r)]
    if not rows:
        return

    seasons = [r["month_label"] for r in rows]
    n = len(rows)
    xt = ",".join(str(i) for i in range(n))
    xtl = ",".join(f"\\small {s}" for s in seasons)

    dc_pts, dk_pts, pv_pts = [], [], []
    for i, r in enumerate(rows):
        base_c = _f(r, "Cumulative_EqualService_Carbon_g")
        base_k = _f(r, "Cumulative_EqualService_Cost_EUR")
        dC = (_f(r, "Cumulative_Carbon_g") - base_c) / base_c * 100
        dK = (_f(r, "Cumulative_Cost_EUR")  - base_k) / base_k * 100
        pv = _f(r, "Cumulative_PV_Energy_kWh") / 1000.0   # → MWh
        dc_pts.append(f"({i},{dC:.2f})")
        dk_pts.append(f"({i},{dK:.2f})")
        pv_pts.append(f"({i},{pv:.1f})")

    dc_coords = " ".join(dc_pts)
    dk_coords = " ".join(dk_pts)
    pv_coords = " ".join(pv_pts)

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.78\\textwidth, height=5.5cm,
    ybar=2pt, bar width=8pt,
    xtick={{{xt}}}, xticklabels={{{xtl}}},
    ylabel={{\\% change vs equal-service baseline}},
    grid=major, grid style={{gray!15}},
    title={{(a) Carbon \\& cost savings by season}}, title style={{font=\\small}},
    legend style={{font=\\tiny, at={{(0.5,-0.38)}}, anchor=north, legend columns=2}},
    enlargelimits=0.18,
]
\\addplot[fill=blue!60, draw=blue!80!black] coordinates {{ {dc_coords} }};
\\addlegendentry{{Carbon $\\Delta$}}
\\addplot[fill=orange!70, draw=orange!90!black] coordinates {{ {dk_coords} }};
\\addlegendentry{{Cost $\\Delta$}}
\\draw[gray, dashed] (axis cs:-1,0) -- (axis cs:{n},0);
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-28mm,
    width=0.78\\textwidth, height=5.5cm,
    ybar, bar width=14pt,
    xtick={{{xt}}}, xticklabels={{{xtl}}},
    ylabel={{PV yield [MWh]}},
    grid=major, grid style={{gray!15}},
    title={{(b) PV yield by season}}, title style={{font=\\small}}, ymin=0,
    enlargelimits=0.18,
]
\\addplot[fill=yellow!70!orange, draw=orange!80!black] coordinates {{ {pv_coords} }};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Seasonal sensitivity of the reference configuration (4\\,MWh BESS, 1\\,MW PV, full EMS).}}
\\label{{fig:res_seasonal}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis6_seasonal.tex", body)


def fig_axis7() -> None:
    """Two-panel line plot: carbon savings and cost savings vs ω_c/ω_p, per season.

    X axis: weight ratio (7 discrete points mapped to integers 0..6).
    Y axis: % savings vs equal-service baseline (negative = better).
    One line per season (4 lines per panel).
    The spread between lines reveals how sensitive the optimal tuning is per season.
    """
    rows = [r for r in _read_csv(RESULTS / "axis7_seasonal_pareto.csv") if _is_valid(r)]
    if not rows:
        return

    # NB: the carbon-only configuration has omega_p = 0, i.e. an undefined
    # (division-by-zero) ratio; we place it at a finite categorical tick labelled
    # "C-only" rather than plotting an infinite coordinate.
    RATIO_TO_X = {0.0: 0, 0.1: 1, 0.33: 2, 1.0: 3, 3.0: 4, 10.0: 5, float("inf"): 6}
    XTICKLABELS = r"cost-only,price-dom,price-strong,balanced,carbon-strong,carbon-dom,carbon-only"
    SEASON_STYLE = {
        "winter": ("blue!70!black",  "solid",      "*"),
        "spring": ("green!60!black", "dashed",     "triangle*"),
        "summer": ("red!70!black",   "dotted",     "square*"),
        "autumn": ("orange!70!black","dash dot",   "diamond*"),
    }
    SEASON_ORDER = ["winter", "spring", "summer", "autumn"]
    MONTH_LABEL  = {"winter": "Jan--Feb", "spring": "Apr--May",
                    "summer": "Jul--Aug", "autumn": "Oct--Nov"}

    # Group rows by season
    by_season: dict[str, list[dict]] = {s: [] for s in SEASON_ORDER}
    for r in rows:
        s = r.get("season", "")
        if s in by_season:
            ratio = _f(r, "omega_ratio")
            by_season[s].append((ratio, r))

    for s in SEASON_ORDER:
        by_season[s].sort(key=lambda t: (t[0] == float("inf"), t[0]))

    def _savings_pts(season_rows, metric, baseline_metric):
        pts = []
        for ratio, r in season_rows:
            xi = RATIO_TO_X.get(ratio)
            if xi is None:
                # Round to nearest key
                xi = min(RATIO_TO_X, key=lambda k: abs(k - ratio) if k != float("inf") else 1e9)
                xi = RATIO_TO_X[xi]
            base = _f(r, baseline_metric)
            val  = _f(r, metric)
            if math.isnan(base) or base == 0:
                continue
            pct = (val - base) / base * 100.0
            pts.append(f"({xi},{pct:.2f})")
        return " ".join(pts)

    carbon_plots, cost_plots = [], []
    for s in SEASON_ORDER:
        color, style, mark = SEASON_STYLE[s]
        ml = MONTH_LABEL[s]
        c_pts = _savings_pts(by_season[s], "Cumulative_Carbon_g", "Cumulative_EqualService_Carbon_g")
        k_pts = _savings_pts(by_season[s], "Cumulative_Cost_EUR",  "Cumulative_EqualService_Cost_EUR")
        plot_opts = (f"mark={mark}, mark size=2pt, {color}, {style}, very thick")
        carbon_plots.append(
            f"\\addplot[{plot_opts}] coordinates {{ {c_pts} }};\n"
            f"\\addlegendentry{{{ml}}}"
        )
        cost_plots.append(
            f"\\addplot[{plot_opts}] coordinates {{ {k_pts} }};\n"
            f"\\addlegendentry{{{ml}}}"
        )

    n_x = len(RATIO_TO_X)
    xt  = ",".join(str(i) for i in range(n_x))

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.82\\textwidth, height=6.0cm,
    xtick={{{xt}}}, xticklabels={{{XTICKLABELS}}}, x tick label style={{font=\\scriptsize, rotate=30, anchor=east}},
    xlabel={{Objective weighting (cost-leaning $\\rightarrow$ carbon-leaning)}},
    ylabel={{Carbon savings [\\%]}},
    grid=major, grid style={{gray!15}},
    title={{(a) Carbon savings by season}}, title style={{font=\\small}},
    legend style={{font=\\tiny, at={{(0.5,-0.40)}}, anchor=north, legend columns=2}},
]
{chr(10).join(carbon_plots)}
\\draw[gray, dashed] (axis cs:-0.5,0) -- (axis cs:{n_x - 0.5},0);
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-32mm,
    width=0.82\\textwidth, height=6.0cm,
    xtick={{{xt}}}, xticklabels={{{XTICKLABELS}}}, x tick label style={{font=\\scriptsize, rotate=30, anchor=east}},
    xlabel={{Objective weighting (cost-leaning $\\rightarrow$ carbon-leaning)}},
    ylabel={{Cost savings [\\%]}},
    grid=major, grid style={{gray!15}},
    title={{(b) Cost savings by season}}, title style={{font=\\small}},
    legend style={{font=\\tiny, at={{(0.5,-0.40)}}, anchor=north, legend columns=2}},
]
{chr(10).join(cost_plots)}
\\draw[gray, dashed] (axis cs:-0.5,0) -- (axis cs:{n_x - 0.5},0);
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Seasonal weight-ratio sensitivity: carbon savings (a) and cost savings (b) relative to the equal-service baseline across all four seasonal windows, as a function of the objective weight ratio $\\omega_c/\\omega_p$.}}
\\label{{fig:res_seasonal_pareto}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis7_seasonal_pareto.tex", body)


def fig_axis8() -> None:
    """Grid-limit sweep (scope-shift scenario): total carbon and backup/unserved
    energy vs the contracted connection capacity, compared between the two
    connection models — shared transformer (DC headroom = capacity − background)
    and dedicated feeder (DC sees the full nameplate)."""
    rows = [r for r in _read_csv(RESULTS / "axis8_gridlimit.csv") if _is_valid(r)]
    if not rows:
        return

    # Split by connection model. Rows from before the shared/dedicated split have
    # no "transformer" column → treat them as the shared variant so old CSVs and
    # figures still render with a single series.
    shared    = [r for r in rows if (r.get("transformer") or "shared") == "shared"]
    dedicated = [r for r in rows if r.get("transformer") == "dedicated"]

    def _series(subset, fn):
        out = []
        for r in sorted(subset, key=lambda r: _f(r, "grid_mw")):
            y = fn(r)
            if y == y:  # skip NaN
                out.append(f"    ({_f(r, 'grid_mw'):g},{y:.3f})")
        return "\n".join(out)

    def _plot(subset, fn, style, legend):
        s = _series(subset, fn)
        if not s.strip():
            return ""
        return (f"\\addplot[{style}] coordinates {{\n{s}\n}};\n"
                f"\\addlegendentry{{{legend}}}")

    # Panel (a): total carbon. Shared solid, dedicated dashed.
    carbon_sh = _plot(shared,    lambda r: _f(r, "Cumulative_Carbon_g") / 1e6,
                      "mark=*, blue!70!black, very thick", "Total carbon (shared)")
    carbon_de = _plot(dedicated, lambda r: _f(r, "Cumulative_Carbon_g") / 1e6,
                      "mark=o, blue!70!black, very thick, dashed", "Total carbon (dedicated)")

    # Panel (b): backup (diesel) served + unserved, both models.
    backup_sh   = _plot(shared,    lambda r: _f(r, "Cumulative_Backup_Energy_kWh") / 1000.0,
                        "mark=square*, orange!85!black, thick", "Backup served (shared)")
    backup_de   = _plot(dedicated, lambda r: _f(r, "Cumulative_Backup_Energy_kWh") / 1000.0,
                        "mark=square, orange!85!black, thick, dashed", "Backup served (dedicated)")
    unserved_sh = _plot(shared,    lambda r: _f(r, "Cumulative_Unserved_kWh") / 1000.0,
                        "mark=*, red!80!black, very thick", "Unserved (shared)")
    unserved_de = _plot(dedicated, lambda r: _f(r, "Cumulative_Unserved_kWh") / 1000.0,
                        "mark=o, red!80!black, very thick, dashed", "Unserved (dedicated)")

    panel_a = "\n".join(p for p in (carbon_sh, carbon_de) if p)
    panel_b = "\n".join(p for p in (unserved_sh, unserved_de, backup_sh, backup_de) if p)

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.78\\textwidth, height=5.0cm,
    xlabel={{Grid connection capacity [MW]}}, ylabel={{Carbon [tCO$_2$]}},
    grid=major, grid style={{gray!15}}, title={{(a) Total carbon: shared vs dedicated}},
    title style={{font=\\small}}, legend pos=north east, legend style={{font=\\tiny}},
]
{panel_a}
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-18mm,
    width=0.78\\textwidth, height=5.0cm,
    xlabel={{Grid connection capacity [MW]}}, ylabel={{Energy [MWh]}},
    grid=major, grid style={{gray!15}}, title={{(b) Unserved and backup energy: shared vs dedicated}},
    title style={{font=\\small}}, ymin=0, legend pos=north east, legend style={{font=\\tiny}},
]
{panel_b}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Grid-limit sweep under both connection models. A \\emph{{dedicated}} feeder serves the load with negligible backup or unserved energy; a \\emph{{shared}} transformer, whose headroom is the nameplate minus the background load, is periodically congested and falls back on battery depletion and Scope-1 backup dispatch.}}
\\label{{fig:res_gridlimit}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis8_gridlimit.tex", body)


def fig_axis9() -> None:
    """Multi-seed Monte Carlo: unserved energy for the MPC reference vs the
    static plan across seeds, showing whether the MPC gain survives noise."""
    rows = [r for r in _read_csv(RESULTS / "axis9_seed.csv") if _is_valid(r)]
    if not rows:
        return

    def _u(r):
        return _f(r, "Cumulative_Unserved_kWh") / 1000.0

    mpc  = {int(_f(r, "seed")): _u(r) for r in rows if r.get("variant") == "mpc" and _f(r, "seed") == _f(r, "seed")}
    stat = {int(_f(r, "seed")): _u(r) for r in rows if r.get("variant") == "static" and _f(r, "seed") == _f(r, "seed")}
    seeds = sorted(set(mpc) | set(stat))
    if not seeds:
        return

    xt  = ",".join(str(i) for i in range(len(seeds)))
    xtl = ",".join(str(s) for s in seeds)
    mpc_c  = " ".join(f"({i},{mpc[s]:.3f})"  for i, s in enumerate(seeds) if s in mpc  and mpc[s] == mpc[s])
    stat_c = " ".join(f"({i},{stat[s]:.3f})" for i, s in enumerate(seeds) if s in stat and stat[s] == stat[s])

    mpc_vals  = [mpc[s]  for s in seeds if s in mpc]
    stat_vals = [stat[s] for s in seeds if s in stat]
    mpc_mean  = sum(mpc_vals) / len(mpc_vals)   if mpc_vals  else float("nan")
    stat_mean = sum(stat_vals) / len(stat_vals) if stat_vals else float("nan")

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    width=0.78\\textwidth, height=6.0cm,
    xtick={{{xt}}}, xticklabels={{{xtl}}},
    xlabel={{Seed}}, ylabel={{$\\widetilde{{L}}_{{unserved,T}}$ [MWh]}},
    grid=major, grid style={{gray!15}}, ymin=0,
    legend pos=north east, legend style={{font=\\tiny}},
    title={{Unserved energy across seeds: MPC vs.\\ static plan}}, title style={{font=\\small}},
]
\\addplot[only marks, mark=*, mark size=2.5pt, blue!70!black] coordinates {{ {mpc_c} }};
\\addlegendentry{{MPC (mean {mpc_mean:.1f}\\,MWh)}}
\\addplot[only marks, mark=square*, mark size=2.5pt, red!70!black] coordinates {{ {stat_c} }};
\\addlegendentry{{Static (mean {stat_mean:.1f}\\,MWh)}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Multi-seed sensitivity of the intraday re-planner: cumulative unserved energy for the MPC reference and the static day-ahead plan across {len(seeds)} seeds. The MPC advantage is meaningful only if its spread sits consistently below the static plan's.}}
\\label{{fig:res_seed}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis9_seed.tex", body)


def fig_axis10() -> None:
    """SOC-baseline penalty vs weight response: carbon saving for cost-only and
    carbon-only at each w_soc_low level. The widening gap as w_soc_low falls is
    the test of whether the penalty (not just signal co-directionality) flattens
    the weight response."""
    rows = [r for r in _read_csv(RESULTS / "axis10_socbase.csv") if _is_valid(r)]
    if not rows:
        return

    levels = sorted({_f(r, "w_soc_low") for r in rows}, reverse=True)

    def saving(r):
        base = _f(r, "Cumulative_EqualService_Carbon_g")
        val = _f(r, "Cumulative_Carbon_g")
        return (val - base) / base * 100.0 if base and base == base else float("nan")

    def pts_for(weight):
        out = []
        for i, lv in enumerate(levels):
            match = [r for r in rows if _f(r, "w_soc_low") == lv and r.get("weight_label") == weight]
            if match:
                out.append(f"({i},{saving(match[0]):.2f})")
        return " ".join(out)

    cost_pts   = pts_for("cost_only")
    carbon_pts = pts_for("carbon_only")
    xt  = ",".join(str(i) for i in range(len(levels)))
    xtl = ",".join((f"{lv:g}" if lv > 0 else "0 (off)") for lv in levels)

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    width=0.78\\textwidth, height=6.0cm,
    xtick={{{xt}}}, xticklabels={{{xtl}}},
    xlabel={{SOC-baseline penalty $\\omega_s$}}, ylabel={{Carbon saving [\\%]}},
    grid=major, grid style={{gray!15}},
    legend pos=north east, legend style={{font=\\tiny}},
    title={{Weight response vs.\\ SOC-baseline penalty}}, title style={{font=\\small}},
]
\\addplot[mark=*, blue!70!black, very thick] coordinates {{ {cost_pts} }};
\\addlegendentry{{cost-only}}
\\addplot[mark=square*, red!70!black, very thick] coordinates {{ {carbon_pts} }};
\\addlegendentry{{carbon-only}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Carbon saving for the two extreme weight settings (cost-only and carbon-only) as the SOC-baseline penalty $\\omega_s$ is relaxed from its default ($10^6$) to off (0). A widening gap between the two curves as $\\omega_s$ falls indicates that the penalty, not only carbon-price co-directionality, suppresses the objective-weight response.}}
\\label{{fig:res_socbase}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis10_socbase.tex", body)


def fig_npv() -> None:
    """Two-panel NPV figure: NPV vs BESS capacity (axis2) and NPV vs PV capacity (axis3)."""
    rows2 = [r for r in _read_csv(RESULTS / "axis2_bess.csv") if _is_valid(r)]
    rows3 = [r for r in _read_csv(RESULTS / "axis3_pv.csv") if _is_valid(r)]
    if not rows2 or not rows3:
        return

    # Skip any non-finite NPV (e.g. a division-by-zero artefact) so the plot
    # never contains an infinite coordinate.
    coords2 = "\n".join(
        f"    ({_f(r,'capacity_mwh'):g},{_f(r,'NPV_EUR')/1e3:.1f})"
        for r in rows2 if math.isfinite(_f(r, "NPV_EUR"))
    )
    coords3 = "\n".join(
        f"    ({_f(r,'pv_mw'):g},{_f(r,'NPV_EUR')/1e3:.1f})"
        for r in rows3 if math.isfinite(_f(r, "NPV_EUR"))
    )

    body = r"""% Auto-generated by sweep/make_figures.py; do not edit
\begin{figure}[ht]
\centering
\begin{tikzpicture}
\begin{axis}[
    name=p1,
    width=0.78\textwidth, height=5.5cm,
    xlabel={$E_{bat}$ [MWh]}, ylabel={NPV [kEUR]},
    grid=major, grid style={gray!15},
    title={(a) NPV vs.\ BESS capacity}, title style={font=\small},
]
\addplot[mark=*, blue!70!black, very thick] coordinates {
""" + coords2 + r"""
};
\addplot[gray, dashed] coordinates {(0,0) (16,0)};
\node[gray, font=\tiny, anchor=south west] at (axis cs:0,0) {Break-even};
\end{axis}
\begin{axis}[
    name=p2, at={(p1.south west)}, anchor=north west, yshift=-18mm,
    width=0.78\textwidth, height=5.5cm,
    xlabel={PV capacity [MW]}, ylabel={NPV [kEUR]},
    grid=major, grid style={gray!15},
    title={(b) NPV vs.\ PV capacity}, title style={font=\small},
]
\addplot[mark=*, green!60!black, very thick] coordinates {
""" + coords3 + r"""
};
\addplot[gray, dashed] coordinates {(0,0) (5,0)};
\node[gray, font=\tiny, anchor=south west] at (axis cs:0,0) {Break-even};
\end{axis}
\end{tikzpicture}
\caption{10-year NPV (5\% discount rate, BESS CAPEX 200\,EUR/kWh, O\&M 10\,EUR/kW/yr) as a function of BESS nameplate capacity~(a) and installed PV capacity~(b).}
\label{fig:res_npv}
\end{figure}
"""
    _write(FIG_DIR / "fig_npv.tex", body)


def _pct(val: float, base: float, decimals: int = 2) -> str:
    if math.isnan(val) or math.isnan(base) or base == 0:
        return r"\textit{n/a}"
    return f"{(val - base) / base * 100:.{decimals}f}\\%"


def _keur(val: float) -> str:
    if math.isnan(val):
        return r"\textit{n/a}"
    return f"{val / 1e3:.0f}"


def generate_tables() -> None:
    """Write self-contained LaTeX table snippets to FIG_DIR."""

    # ── Table 1: Sweep-axis design overview ──────────────────────────────────
    body = r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{llll}
\toprule
\textbf{Axis} & \textbf{Research question} & \textbf{Parameter varied} & \textbf{Values swept} \\
\midrule
1 & RQ1: objective trade-offs & $\omega_c / \omega_p$ & $0,\,0.1,\,\tfrac{1}{3},\,1,\,3,\,10$, carbon-only \\
2 & RQ2: BESS marginal benefit & $E_{bat}$ [MWh] & $0,\,1,\,2,\,4,\,8,\,16$ \\
3 & RQ3a: PV sizing & PV [MW] & $0,\,0.5,\,1,\,2,\,5$ \\
4 & RQ3b: backup generation & Backup [MW] & $0,\,2,\,5,\,10$ \\
5 & RQ4: intraday replanning & SoC-drift $\times$ demand-spike & $4 \times 4 = 16$ cells \\
6 & Seasonal sensitivity & Start date & Winter, Spring, Summer, Autumn \\
7 & Seasonal weight optimality & $\omega_c / \omega_p \times$ season & $7 \times 4 = 28$ runs \\
8 & RQ3: scope shift & Grid cap. [MW] $\times$ \{shared, dedicated\} & $5 \times 2 = 10$ runs \\
9 & RQ4: seed robustness & Seed $\times$ \{MPC, static\} & $5 \times 2 = 10$ runs \\
10 & RQ1: SOC-penalty effect & $\omega_s \times \{$cost-only, carbon-only$\}$ & $3 \times 2 = 6$ runs \\
11 & RQ1: single-objective floors & Sole active objective & min-carbon, min-cost, max-availability \\
12 & 24/7 carbon-free operation & CFE floor $\phi$ [\%] & $0,\,50,\,70,\,85,\,100$ \\
\bottomrule
\end{tabular}
\caption{Summary of the twelve experimental axes, their corresponding research questions, and swept parameter ranges; all axes use the Jan–Feb 2024 reference window except Axes~6 and~7 which vary the start date.}
\label{tab:sweep_axes}
\end{table}
"""
    _write(FIG_DIR / "tab_sweep_axes.tex", body)

    # ── Table 2: Axis 1 Pareto results ───────────────────────────────────────
    rows = [r for r in _read_csv(RESULTS / "axis1_pareto.csv") if _is_valid(r)]
    if rows:
        base_c = _f(rows[0], "Cumulative_EqualService_Carbon_g")
        base_k = _f(rows[0], "Cumulative_EqualService_Cost_EUR")
        labels = {
            "cost_only": r"Cost-only ($\omega_c/\omega_p=0$)",
            "p_dominant": r"Price-dominant (0.1)",
            "p_strong": r"Price-strong ($\tfrac{1}{3}$)",
            "balanced": r"Balanced (1)",
            "c_strong": r"Carbon-strong (3)",
            "c_dominant": r"Carbon-dominant (10)",
            "carbon_only": r"Carbon-only",
        }
        rows_tex = ""
        for r in rows:
            lbl = labels.get(r["label"], r["label"])
            dc = _pct(_f(r, "Cumulative_Carbon_g"), _f(r, "Cumulative_EqualService_Carbon_g"))
            dk = _pct(_f(r, "Cumulative_Cost_EUR"), _f(r, "Cumulative_EqualService_Cost_EUR"))
            npv = _keur(_f(r, "NPV_EUR"))
            rows_tex += f"    {lbl} & {dc} & {dk} & {npv} \\\\\n"
        body = r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{lrrr}
\toprule
\textbf{Weight configuration} & $\Delta\widetilde{C}_T$ & $\Delta\widetilde{K}_T$ & \textbf{NPV} [kEUR] \\
\midrule
""" + rows_tex + r"""\bottomrule
\end{tabular}
\caption{Axis~1 weight-ratio sweep: percentage savings in carbon and cost relative to the equal-service baseline and 10-year NPV for each of the seven configurations.}
\label{tab:axis1_results}
\end{table}
"""
        _write(FIG_DIR / "tab_axis1.tex", body)

    # ── Table 3: Axis 2 BESS sizing results ──────────────────────────────────
    rows = [r for r in _read_csv(RESULTS / "axis2_bess.csv") if _is_valid(r)]
    if rows:
        base_c = _f(rows[0], "Cumulative_EqualService_Carbon_g")
        base_k = _f(rows[0], "Cumulative_EqualService_Cost_EUR")
        rows_tex = ""
        for r in rows:
            cap = _f(r, "capacity_mwh")
            dc = _pct(_f(r, "Cumulative_Carbon_g"), _f(r, "Cumulative_EqualService_Carbon_g"))
            dk = _pct(_f(r, "Cumulative_Cost_EUR"), _f(r, "Cumulative_EqualService_Cost_EUR"))
            u = _f(r, "Cumulative_Unserved_kWh") / 1000.0
            npv = _keur(_f(r, "NPV_EUR"))
            lcos_v = _f(r, "LCOS_EUR_per_kWh")
            lcos = f"{lcos_v:.3f}" if not math.isnan(lcos_v) else r"\textit{n/a}"
            soc = f"{_f(r,'Min_SOC_Overall'):.0f}\\%"
            rows_tex += (
                f"    {cap:g}\\,MWh & {dc} & {dk} & {u:.0f}\\,MWh "
                f"& {npv} & {lcos} & {soc} \\\\\n"
            )
        body = r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{lrrrrrr}
\toprule
\textbf{BESS capacity} & $\Delta\widetilde{C}_T$ & $\Delta\widetilde{K}_T$
  & \textbf{Unserved} & \textbf{NPV} [kEUR] & \textbf{LCOS} [EUR/kWh] & $\text{SoC}_\text{min}$ \\
\midrule
""" + rows_tex + r"""\bottomrule
\end{tabular}
\caption{Axis~2 BESS sizing sweep: carbon and cost savings, unserved energy, 10-year NPV, LCOS, and minimum SoC as a function of nameplate capacity at the carbon-anchored weight setting.}
\label{tab:axis2_results}
\end{table}
"""
        _write(FIG_DIR / "tab_axis2.tex", body)

    # ── Table 4: Axis 4 backup scope shift ───────────────────────────────────
    rows = [r for r in _read_csv(RESULTS / "axis4_backup.csv") if _is_valid(r)]
    if rows:
        base_c = _f(rows[0], "Cumulative_EqualService_Carbon_g")
        rows_tex = ""
        for r in rows:
            mw = _f(r, "backup_mw")
            c_tc = _f(r, "Cumulative_Carbon_g") / 1e6
            dc = _pct(_f(r, "Cumulative_Carbon_g"), _f(r, "Cumulative_EqualService_Carbon_g"))
            bk = _f(r, "Cumulative_Backup_Energy_kWh") / 1000.0   # MWh actually dispatched
            u = _f(r, "Cumulative_Unserved_kWh") / 1000.0
            scope2_avoided = bk * 250.0 / 1e3  # tCO2 of grid import the backup displaced
            scope1 = _f(r, "Cumulative_Scope1_Carbon_g") / 1e6  # tCO2 actually emitted on-site
            rows_tex += (
                f"    {mw:g}\\,MW & {c_tc:.1f} & {dc} & {bk:.0f}\\,MWh"
                f" & {scope2_avoided:.1f}\\,tCO$_2$ & {scope1:.1f}\\,tCO$_2$"
                f" & {u:.0f}\\,MWh \\\\\n"
            )
        body = r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{lrrrrrr}
\toprule
\textbf{Backup cap.} & $\widetilde{C}_T$ [tCO$_2$] & $\Delta\widetilde{C}_T$
  & \textbf{Dispatched} & \textbf{Scope~2 avoided} & \textbf{Scope~1 emitted} & \textbf{Unserved} \\
\midrule
""" + rows_tex + r"""\bottomrule
\end{tabular}
\caption{Axis~4 backup-generator sweep: cumulative carbon, Scope~2 avoided, Scope~1 emitted (at 600\,gCO$_2$/kWh), and unserved energy as backup capacity increases from 0 to 10\,MW.}
\label{tab:axis4_results}
\end{table}
"""
        _write(FIG_DIR / "tab_axis4.tex", body)

    # ── Table 5: Axis 6 seasonal results ─────────────────────────────────────
    rows = [r for r in _read_csv(RESULTS / "axis6_seasonal.csv") if _is_valid(r)]
    if rows:
        rows_tex = ""
        for r in rows:
            lbl = r.get("month_label", r["season"])
            base_c = _f(r, "Cumulative_EqualService_Carbon_g")
            base_k = _f(r, "Cumulative_EqualService_Cost_EUR")
            dc = _pct(_f(r, "Cumulative_Carbon_g"), _f(r, "Cumulative_EqualService_Carbon_g"))
            dk = _pct(_f(r, "Cumulative_Cost_EUR"), _f(r, "Cumulative_EqualService_Cost_EUR"))
            pv = _f(r, "Cumulative_PV_Energy_kWh") / 1000.0
            cfe = f"{_f(r,'CFE_Score')*100:.2f}\\%"
            rows_tex += f"    {lbl} & {pv:.1f}\\,MWh & {dc} & {dk} & {cfe} \\\\\n"
        body = r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{lrrrr}
\toprule
\textbf{Season} & \textbf{PV yield} & $\Delta\widetilde{C}_T$ & $\Delta\widetilde{K}_T$ & \textbf{CFE score} \\
\midrule
""" + rows_tex + r"""\bottomrule
\end{tabular}
\caption{Axis~6 seasonal sensitivity: PV yield, carbon savings, cost savings, and CFE score for the reference configuration across four 60-day windows, each measured against a season-matched equal-service baseline.}
\label{tab:axis6_seasonal}
\end{table}
"""
        _write(FIG_DIR / "tab_axis6.tex", body)

    print(f"Wrote tables to {FIG_DIR}/")


def fig_axis12() -> None:
    """Carbon-free-operation sweep: realized grid carbon-free share, and the
    carbon/unserved price of raising the CFE floor toward 24/7 green operation."""
    rows = [r for r in _read_csv(RESULTS / "axis12_cfe.csv") if _is_valid(r)]
    if not rows:
        return

    SEASON_STYLE = {
        "winter": ("blue!70!black",  "solid",      "*"),
        "spring": ("green!60!black", "dashed",     "triangle*"),
        "summer": ("red!70!black",   "dotted",     "square*"),
        "autumn": ("orange!70!black","dash dot",   "diamond*"),
    }
    SEASON_ORDER = ["winter", "spring", "summer", "autumn"]
    MONTH_LABEL  = {"winter": "Jan--Feb", "spring": "Apr--May",
                    "summer": "Jul--Aug", "autumn": "Oct--Nov"}

    by_season: dict[str, list[dict]] = {s: [] for s in SEASON_ORDER}
    for r in rows:
        s = r.get("season")
        if not s:
            s = "winter"
        if s in by_season:
            by_season[s].append(r)
            
    for s in SEASON_ORDER:
        by_season[s].sort(key=lambda r: _f(r, "cfe_floor"))

    def _series(season_rows, fn):
        out = []
        for r in season_rows:
            y = fn(r)
            if y == y:  # skip NaN
                out.append(f"    ({_f(r, 'cfe_floor') * 100:g},{y:.3f})")
        return "\n".join(out)

    realized_plots, carbon_plots, unserved_plots = [], [], []

    for s in SEASON_ORDER:
        if not by_season[s]: continue
        color, style, mark = SEASON_STYLE[s]
        ml = MONTH_LABEL[s]
        plot_opts = f"mark={mark}, mark size=2pt, {color}, {style}, very thick"
        
        realized = _series(by_season[s], lambda r: _f(r, "Grid_CFE_Pct"))
        if realized.strip():
            realized_plots.append(f"\\addplot[{plot_opts}] coordinates {{\n{realized}\n}};\n\\addlegendentry{{{ml}}}")

        carbon = _series(by_season[s], lambda r: _f(r, "Cumulative_Carbon_g") / 1e6)
        if carbon.strip():
            carbon_plots.append(f"\\addplot[{plot_opts}] coordinates {{\n{carbon}\n}};\n\\addlegendentry{{{ml}}}")
            
        unserved = _series(by_season[s], lambda r: _f(r, "Cumulative_Unserved_kWh") / 1000.0)
        if unserved.strip():
            unserved_plots.append(f"\\addplot[{plot_opts}] coordinates {{\n{unserved}\n}};\n\\addlegendentry{{{ml}}}")

    body = f"""% Auto-generated by sweep/make_figures.py; do not edit
\\begin{{figure}}[ht]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
    name=p1,
    width=0.78\\textwidth, height=4.8cm,
    xlabel={{Carbon-free floor [\\%]}}, ylabel={{Realized grid CFE [\\%]}},
    grid=major, grid style={{gray!15}}, title={{(a) Realized grid carbon-free share by season}},
    title style={{font=\\small}}, legend pos=north west, legend style={{font=\\tiny, legend columns=2}},
]
{chr(10).join(realized_plots)}
\\addplot[gray, dashed, thick] coordinates {{(0,0) (100,100)}};
\\addlegendentry{{Floor (y=x)}}
\\end{{axis}}
\\begin{{axis}}[
    name=p2, at={{(p1.south west)}}, anchor=north west, yshift=-16mm,
    width=0.78\\textwidth, height=4.8cm,
    xlabel={{Carbon-free floor [\\%]}}, ylabel={{Carbon [tCO$_2$]}},
    grid=major, grid style={{gray!15}}, title={{(b) Total carbon by season}},
    title style={{font=\\small}}, ymin=0, legend pos=south west, legend style={{font=\\tiny, legend columns=2}},
]
{chr(10).join(carbon_plots)}
\\end{{axis}}
\\begin{{axis}}[
    name=p3, at={{(p2.south west)}}, anchor=north west, yshift=-16mm,
    width=0.78\\textwidth, height=4.8cm,
    xlabel={{Carbon-free floor [\\%]}}, ylabel={{Unserved [MWh]}},
    grid=major, grid style={{gray!15}}, title={{(c) Unserved energy by season}},
    title style={{font=\\small}}, ymin=0, legend pos=north west, legend style={{font=\\tiny, legend columns=2}},
]
{chr(10).join(unserved_plots)}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Seasonal Carbon-free-operation sweep: as the carbon-free floor on grid imports rises, the realized grid carbon-free share tracks it (a). Total carbon falls (b) and unserved energy rises (c) as the battery is increasingly relied on to ride through carbon-intensive grid periods, with severity varying by season.}}
\\label{{fig:res_cfe}}
\\end{{figure}}
"""
    _write(FIG_DIR / "fig_axis12_cfe.tex", body)


def make_all() -> None:
    fig_axis1()
    fig_axis2()
    fig_axis3()
    fig_axis4()
    fig_axis5()
    fig_combined_pareto()
    fig_overhead()
    fig_axis6()
    fig_axis7()
    fig_axis8()
    fig_axis9()
    fig_axis10()
    fig_axis12()
    fig_npv()
    generate_tables()
    print(f"Wrote figure snippets to {FIG_DIR}/")


if __name__ == "__main__":
    make_all()
